# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "C:\\FH\\WS25\\SWEN3\\PAPERLESS_DV_LM_IR\\Paperless"
      dockerfile: "API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "api:dev"
    ports: []
    volumes:
    - "C:\\FH\\WS25\\SWEN3\\PAPERLESS_DV_LM_IR\\Paperless\\API:/app:rw"
    - "C:\\FH\\WS25\\SWEN3\\PAPERLESS_DV_LM_IR\\Paperless:/src:rw"
    - "C:\\Users\\Luki\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  batchworker:
    build:
      context: "C:\\FH\\WS25\\SWEN3\\PAPERLESS_DV_LM_IR\\Paperless"
      dockerfile: "BatchWorker/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/BatchWorker.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "batchworker:dev"
    ports: []
    volumes:
    - "C:\\FH\\WS25\\SWEN3\\PAPERLESS_DV_LM_IR\\Paperless\\BatchWorker:/app:rw"
    - "C:\\FH\\WS25\\SWEN3\\PAPERLESS_DV_LM_IR\\Paperless:/src:rw"
    - "C:\\Users\\Luki\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
  genaiworker:
    build:
      context: "C:\\FH\\WS25\\SWEN3\\PAPERLESS_DV_LM_IR\\Paperless"
      dockerfile: "GenAIWorker/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/GenAIWorker.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "genaiworker:dev"
    ports: []
    volumes:
    - "C:\\FH\\WS25\\SWEN3\\PAPERLESS_DV_LM_IR\\Paperless\\GenAIWorker:/app:rw"
    - "C:\\FH\\WS25\\SWEN3\\PAPERLESS_DV_LM_IR\\Paperless:/src:rw"
    - "C:\\Users\\Luki\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
  indexingworker:
    build:
      context: "C:\\FH\\WS25\\SWEN3\\PAPERLESS_DV_LM_IR\\Paperless"
      dockerfile: "IndexingWorker/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/IndexingWorker.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "indexingworker:dev"
    ports: []
    volumes:
    - "C:\\FH\\WS25\\SWEN3\\PAPERLESS_DV_LM_IR\\Paperless\\IndexingWorker:/app:rw"
    - "C:\\FH\\WS25\\SWEN3\\PAPERLESS_DV_LM_IR\\Paperless:/src:rw"
    - "C:\\Users\\Luki\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
  ocrworker:
    build:
      context: "C:\\FH\\WS25\\SWEN3\\PAPERLESS_DV_LM_IR\\Paperless"
      dockerfile: "OcrWorker/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/OcrWorker.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "ocrworker:dev"
    ports: []
    volumes:
    - "C:\\FH\\WS25\\SWEN3\\PAPERLESS_DV_LM_IR\\Paperless\\OcrWorker:/app:rw"
    - "C:\\FH\\WS25\\SWEN3\\PAPERLESS_DV_LM_IR\\Paperless:/src:rw"
    - "C:\\Users\\Luki\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
  ui:
    build:
      context: "C:\\FH\\WS25\\SWEN3\\PAPERLESS_DV_LM_IR\\Paperless"
      dockerfile: "UI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/UI.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/UI.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "ui:dev"
    ports: []
    volumes:
    - "C:\\FH\\WS25\\SWEN3\\PAPERLESS_DV_LM_IR\\Paperless\\UI:/app:rw"
    - "C:\\FH\\WS25\\SWEN3\\PAPERLESS_DV_LM_IR\\Paperless:/src:rw"
    - "C:\\Users\\Luki\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
